version: "3.8"
services:
  mongo:
    image: geppettotest/mongo-local:april2020
    container_name: mongo-8341
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - ticketsampleapplication783_8341-volume:/data/db
    ports:
      - "27018:27017"
    healthcheck:
      test: echo 'db.runCommand({serverStatus:1}).ok' | mongo admin -u root -p root --quiet | grep 1
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s

  camunda:
    image: geppettodistribution/camunda-local:Jan2021
    container_name: camunda-8341
    ports:
      - "0000:8080"

  authproxy:
    build: ../../../application/services/default_services/authproxy
    image: authproxy-8341
    container_name: authproxy-8341
    ports:
      - "0000:8001"
    env_file: .env
    depends_on:
      - mongo
      - camunda

  securitymanager:
    build: ../../../application/services/default_services/securitymanager
    image: securitymanager-8341
    container_name: securitymanager-8341
    ports:
      - "8003:8003"
    env_file: .env
    depends_on:
      - mongo
      - camunda

  camundaservice:
    build: ../../../application/services/default_services/camunda
    image: camundaservice-8341
    container_name: camundasvc-8341
    ports:
      - "8002:8002"
    env_file: .env
    depends_on:
      - mongo
      - camunda
      - securitymanager

  apigateway:
    build: ../../../application/services/custom_services/apigateway
    image: apigateway-8341
    container_name: apigateway-8341
    ports:
      - "8000:8000"
    env_file: .env
    depends_on:
      - camunda
      - camundaservice
      - authproxy
      - securitymanager
      - ticketsample
      - typessample
      - severitysample



  ticketsample: 
    build: ../../../application/services/custom_services/ticketsample
    image: ticketsample-8341
    container_name: ticketsample-8341
    ports: 
      - 8023:8023
    env_file: .env
    depends_on:
      - mongo

  typessample: 
    build: ../../../application/services/custom_services/typessample
    image: typessample-8341
    container_name: typessample-8341
    ports: 
      - 8024:8024
    env_file: .env
    depends_on:
      - mongo

  severitysample: 
    build: ../../../application/services/custom_services/severitysample
    image: severitysample-8341
    container_name: severitysample-8341
    ports: 
      - 8025:8025
    env_file: .env
    depends_on:
      - mongo


volumes:
  ticketsampleapplication783_8341-volume:
    driver: local
